language: python
python:
  - 3.6
  - 3.7
  - 3.8-dev
install:
  - pip install -r requirements-test.txt
  - pip install -r requirements.txt
before_script:
  - mkdir -p tests/_coverage
script:
  - py.test tests/ --cov watson --cov-report term-missing
after_success:
  - coveralls --verbose
notifications:
  slack:
    secure: c2aJk3xE2by9wWnQRrIH07Y9uhb33PstWPJz2HKe1d/U/kLb7G0G1uPCsnrfkLAzWiQ/MyDWRiGdv4hCdzGXQfw+t17uJvSF0S+vpyqfwtvhHaMs85xbbB4ZVf5/s+ZwrQA8qYtnobUHYkk2yVm0NeYAZSNKwq8EMjwuj8Xo6y8=
